### ISSUE TITLE
[ SECURITY ] Spacing between second-fold and footer

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [acelabini/ibinex-option-one#1]
Suggestion:
Add **margin-bottom: 7.7%** to security.css

> @media only screen and (min-width: 1200px)
#second-fold-container {
    padding-left: 0;
    padding-right: 0;
    **margin-bottom: 7.7%;**
}

Generated:
![image](https://user-images.githubusercontent.com/37060596/38015833-ae73e6cc-329f-11e8-8ae3-e08acf2b7639.png)

Expected:
![image](https://user-images.githubusercontent.com/37060596/38015877-d0217cda-329f-11e8-941a-941ab2e41179.png)

**Comment by AnsellCC** [comment]
@lester-ar-ibinex-tech @seanibinex update pls
