### ISSUE TITLE
[ SERVICES ] Color and size of hamburger menu

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#11]
Tester: Joel Simpao
OS: Windows 10
Browser: Chrome

Expected (left) vs. Actual (right):
![expected actual hamburger color and size](https://user-images.githubusercontent.com/37061492/38189696-dcb8d16c-3693-11e8-9bba-685fd9d1821d.PNG)

**Comment by AnsellCC** [comment]
fixed https://github.com/acelabini/ibinex-option-one/commit/d8ef5ed87ad04a175cc5faa647aa60c0f070c5d1
