### ISSUE TITLE
[ SERVICES ] Number of lines in Services intro

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#13]
Tester: Joel Simpao
OS: Windows 10
Browser: Chrome
Resolution: 1366px width (test environment used by tester)

Given that the page was tested on a 1366px width resolution (less than the 1911px width of the image in the PSD), shouldn't the encircled text occupy at least 2 lines?

Expected:
![expected intro lines](https://user-images.githubusercontent.com/37061492/38190951-270e0a70-3699-11e8-9ad9-63162cb36925.PNG)

Actual:
![actual intro lines](https://user-images.githubusercontent.com/37061492/38190961-319b0628-3699-11e8-9d58-1eb798779d10.PNG)

**Comment by AnsellCC** [comment]
Not that big of an issue. Closing for now.
