### ISSUE TITLE
[ SERVICES ] Currency ticker in nav/header displays wrong data

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#14]
Tester: Joel Simpao
OS: Windows 10
Browser: Chrome

Expected:
![expected nav ticker text](https://user-images.githubusercontent.com/37061492/38191982-5ba0936c-369d-11e8-9686-25cee718ed89.PNG)

Actual:
![actual nav ticker text](https://user-images.githubusercontent.com/37061492/38191993-63f60d76-369d-11e8-876f-93fe2d90afb4.PNG)

**Comment by AnsellCC** [comment]
fixed https://github.com/acelabini/ibinex-option-one/commit/f004a392f98abc7a4542962a92eb2d1d3c54f579
