### ISSUE TITLE
[ SERVICES ] Risk Disclosure text size

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#16]
Tester: Joel Simpao
OS: Windows 10
Browser: Chrome

Expected:
![expected risk disclosure](https://user-images.githubusercontent.com/37061492/38193164-1cc169a4-36a3-11e8-8cc1-68b58dd5dd56.PNG)

Actual:
![actual risk disclosure](https://user-images.githubusercontent.com/37061492/38193168-23c2c608-36a3-11e8-8f14-af840000e036.PNG)

**Comment by AnsellCC** [comment]
Fixed @jsimpao @peterbrionibinex
