### ISSUE TITLE
[ SERVICES ] Contact numbers display as hyperlinks in Microsoft Edge

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#17]
Tester: Joel Simpao
OS: Windows 10
Browser: Microsoft Edge

Expected (Nav/Header):
![expected contact numbers - 1](https://user-images.githubusercontent.com/37061492/38194032-b76fbbaa-36a7-11e8-8443-770e0e6187f0.PNG)

Expected (Footer):
![expected contact numbers - 2](https://user-images.githubusercontent.com/37061492/38194051-ccfc5942-36a7-11e8-9515-1e014b7e9c8b.PNG)

![expected contact numbers - 3](https://user-images.githubusercontent.com/37061492/38194053-d1bb5b5e-36a7-11e8-8a45-e4b851a5531e.PNG)

Actual (Nav/Header):
![actual contact numbers - 1](https://user-images.githubusercontent.com/37061492/38194068-e1d6ad36-36a7-11e8-839c-00b892301758.PNG)

Actual (Footer):
![actual contact numbers - 2](https://user-images.githubusercontent.com/37061492/38194077-eebe6b92-36a7-11e8-980b-461c40e10180.PNG)

![actual contact numbers - 3](https://user-images.githubusercontent.com/37061492/38194080-f3522680-36a7-11e8-8754-d159f9b274fa.PNG)

**Comment by AnsellCC** [comment]
fixed. @jsimpao
