### ISSUE TITLE
Currency ticker in nav/header for mobile

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#18]
**Platform: Mobile**

Wrong data in currency ticker in mobile view.

Expected Result (left) vs. Actual Result (right):
![expected actual nav ticker in mobile](https://user-images.githubusercontent.com/37061492/38226855-26bddf88-372e-11e8-8b85-0f2e3613b6d8.PNG)

**Comment by AnsellCC** [comment]
fixed https://github.com/acelabini/ibinex-option-one/commit/fa57729d77b8bd960bbe41208ab37bcabcc6b6f7 @jsimpao
