### ISSUE TITLE
"join our telegram community" button in nav/header

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#19]
**Platform: Desktop**

In the actual output:
1. The paper airplane icon is more compressed than the expected output.
2. The "join our telegram community" text seems to have a different font weight.
3. The border radius of the box seems to not match the one in the expected output.
4. The paper airplane icon is too close to the "join our telegram community" text.
5. There is not much space between the box and the right edge of the screen.

Expected Result:
![expected telegram community button](https://user-images.githubusercontent.com/37061492/38228124-559c1d0a-3734-11e8-9e62-72704a27b407.PNG)

Actual Result:
![actual telegram community button](https://user-images.githubusercontent.com/37061492/38228127-5b729bdc-3734-11e8-957b-02dfc5b432d5.PNG)

**Comment by AnsellCC** [comment]
problem #5 entirely depends on the user's resolution.

**Comment by AnsellCC** [comment]
@jsimpao @abry-ibinex see commit https://github.com/acelabini/ibinex-option-one/commit/82e12ede70214968857761efa60a5521a266c70c and QA again please

**Comment by jsimpao** [comment]
Tested on screen width of 1366px.
The following issues still persist:

1. The paper airplane icon is more compressed than the expected output.
-- Upon closer inspection, the paper airplane icon used in our website doesn't seem to be exactly the same as that in the PSD screenshot.

2. The "join our telegram community" text seems to have a different font weight.

5. There is not much space between the box and the right edge of the screen.
-- Shouldn't there still be a good amount of distance between the box and the right edge of the screen? Kindly advise on this.

**Comment by AnsellCC** [comment]
regarding 3. It only occurs on 1400px below. The psd provided is 1920px width. I agree there should be a space on the right side but lets wait for input.

**Comment by AnsellCC** [comment]
QA please @jsimpao

**Comment by jsimpao** [comment]
Hi. With regard to no. 4 in the first post:
- The paper airplane icon is too close to the "join our telegram community" text.

Would it be possible to adjust the distance a little bit more to make it similar to the expected output?

Expected Result:
![expected join box](https://user-images.githubusercontent.com/37061492/38239516-8517a2cc-375f-11e8-8d2c-2ddcd6ec5436.PNG)

Actual Result:
![actual join box](https://user-images.githubusercontent.com/37061492/38239520-8a393036-375f-11e8-9959-70542821ac46.PNG)

**Comment by AnsellCC** [comment]
adjusted. For QA again @jsimpao

**Comment by jsimpao** [comment]
Closing this issue now. Thank you!
