### ISSUE TITLE
[CONTACT US] CSS targeting of elements is too general.

### ISSUE THREAD

**Issue by markibinex** [acelabini/ibinex-option-one#2]
![contact_css1](https://user-images.githubusercontent.com/37097473/38126938-4d0d8eaa-3426-11e8-8a5a-0c8735546859.PNG)
![contact_css2](https://user-images.githubusercontent.com/37097473/38126950-5db7e912-3426-11e8-8811-a8e3e6a12226.PNG)

**Comment by AnsellCC** [comment]
@markibinex  QA pls
