### ISSUE TITLE
Risk Disclosure issues with font, spacing, length, etc.

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#24]
**Platform: Mobile**
Resolution: 320px width

Expected Result (left) vs. Actual Result (right):
![expected actual risk disclosure font](https://user-images.githubusercontent.com/37061492/38233388-fbd46890-374c-11e8-924c-6723fa670c7b.PNG)

**Platform: Desktop**
Resolution: 1920px width

Expected Result:
![expected risk disclosure desktop](https://user-images.githubusercontent.com/37061492/38234155-95959088-374f-11e8-9c1d-982cc8a23f86.PNG)

Actual Result:
![actual risk disclosure desktop](https://user-images.githubusercontent.com/37061492/38234835-9ead9272-3751-11e8-8788-02699b927888.PNG)

**Comment by AnsellCC** [comment]
@jsimpao is this for mobile only?

**Comment by jsimpao** [comment]
Updated the issue with the results from desktop view using the same resolution as the PSD image. Actual result is also different from expected output.

**Comment by jsimpao** [comment]
Wait . wrong screenshot. let me try it again.

**Comment by AnsellCC** [comment]
@jsimpao QA please. fixed on https://github.com/acelabini/ibinex-option-one/commit/1195318d5a0dd04cdf3578e23efed4b7b1481cce

**Comment by jsimpao** [comment]
Issue still persists. The actual Risk Disclosure output visually looks longer than the expected output. Please see updated screenshots below. Thanks!

**Platform: Mobile**
Resolution: 320px width

Expected Result (left) vs. Actual Result (right):
![expected actual risk disclosure font - fix 1](https://user-images.githubusercontent.com/37061492/38238410-5140ddc2-375c-11e8-928e-1fd959af52a1.PNG)

**Platform: Desktop**
Resolution: 1920px width

Expected Result:
![expected risk disclosure desktop](https://user-images.githubusercontent.com/37061492/38238489-9243eca6-375c-11e8-9e2a-18c7eb94006b.PNG)

Actual Result:
![actual risk disclosure desktop - fix 1](https://user-images.githubusercontent.com/37061492/38238526-ab59170c-375c-11e8-990c-5e4fa9ba1293.PNG)

**Comment by AnsellCC** [comment]
got it

**Comment by AnsellCC** [comment]
please check https://github.com/acelabini/ibinex-option-one/commit/77e47a87f69c73956beac43e72cc7da0bdb96179

**Comment by abry-ibinex** [comment]
closed for now
