### ISSUE TITLE
Page overflow

### ISSUE THREAD

**Issue by abry-ibinex** [acelabini/ibinex-option-one#27]
**Platform: Desktop & mobile**

Actual result:
![image](https://user-images.githubusercontent.com/37060537/38237719-cbc0349c-36dc-11e8-8177-6b93f3c273c4.png)

**Comment by kgsoriano17** [comment]
I only see the overflow on devtools. will investigate this.

**Comment by abry-ibinex** [comment]
@kgsoriano17 it is because you applied overflow-x hidden on the whole <body>. It is known to be a bad practice. We shouldn't settle for a band-aid approach.

**Comment by kgsoriano17** [comment]
yeah. saw the problem

**Comment by kgsoriano17** [comment]
just added the info for everyone else. trying to fix it
