### ISSUE TITLE
Responsiveness for mobile ( third fold )

### ISSUE THREAD

**Issue by abry-ibinex** [acelabini/ibinex-option-one#30]
Actual result:
![image](https://user-images.githubusercontent.com/37060537/38239911-f6d201be-36e2-11e8-901b-fce35bfdb822.png)

**Comment by jctiru-ibinex** [comment]
Ace added initial fix for responsiveness.

**Comment by jctiru-ibinex** [comment]
Fine tuning responsiveness of third fold help wanted.

**Comment by abry-ibinex** [comment]
Continued to #46
