### ISSUE TITLE
Pricing page distance issues

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#33]
**Platform: iPad Pro (1024 px width)**

Expected Result:
![expected pricing line break](https://user-images.githubusercontent.com/37061492/38240915-79b8b0e8-3763-11e8-9d4f-484959e5fafd.PNG)

Actual Result:
Red Ellipse: Not enough distance.
Orange Ellipse: Too much distance.

**Note: Issue highlighted by the orange ellipse is also present in mobile view.**
![actual pricing line break](https://user-images.githubusercontent.com/37061492/38240934-824a6206-3763-11e8-8a5a-f13363882c75.PNG)

**Comment by abry-ibinex** [comment]
@markibinex The orange issue still persist, Mark.

**Comment by abry-ibinex** [comment]
Thanks, Mark ibinex!
