### ISSUE TITLE
Why Ibinex emulates layout of mobile design on 1024px width

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#38]
**Platform: iPad Pro (1024px width)**

In device having 1024px width, layout simulates mobile design more than desktop design.

Actual Result:
![actual wrong layout on 1024px width](https://user-images.githubusercontent.com/37061492/38245460-bb67e18c-3770-11e8-8765-b2787e54f205.PNG)

Encircled sections below should be center-aligned on desktop width:
![actual wrong layout on 1024px width - 2](https://user-images.githubusercontent.com/37061492/38245467-c050cc18-3770-11e8-9d23-304749ec6410.PNG)

**Comment by jsimpao** [comment]
**Platform: iPad Pro (1024px width)**

Issue still persists. Please see updated screenshot below of output after latest fix.

Actual Result:
![actual wrong layout on 1024px width - fix 1](https://user-images.githubusercontent.com/37061492/38286555-8fff7bd0-37f8-11e8-8fff-603a2eae9b10.PNG)

**Comment by abry-ibinex** [comment]
Thanks mark!
