### ISSUE TITLE
Checkmarks are not properly aligned with adjacent text

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#39]
**Platform: Mobile**

Expected Result (left) vs. Actual Result (right):
![expected actual misaligned checkmarks](https://user-images.githubusercontent.com/37061492/38247228-07ea5f2a-3777-11e8-8828-a82409ecdc12.PNG)

**Comment by abry-ibinex** [comment]
Fixing this issue for mobile destroys it for desktop and vice versa. I suggest apply a new media query for mobile since the measurements for the position-y isn't the same in desktop and mobile.

**Comment by AnsellCC** [comment]
for QA

**Comment by abry-ibinex** [comment]
The positioning issue has been fixed but a new one came up:
![image](https://user-images.githubusercontent.com/37060537/38287878-1387cb96-3782-11e8-9edf-bf86ecb3bf69.png)

**Comment by abry-ibinex** [comment]
Thanks Ansell!
