### ISSUE TITLE
[ WHY ] Inconsistency with text content.

### ISSUE THREAD

**Issue by abry-ibinex** [acelabini/ibinex-option-one#4]
# Please confirm which one to follow.

<hr>

**Expected:**

![image](https://user-images.githubusercontent.com/37060537/38162077-54933034-350d-11e8-878c-def20e34d5fa.png)

**Generated:**

![image](https://user-images.githubusercontent.com/37060537/38161974-4d2a520c-350b-11e8-90a1-e2ab43314a34.png)

<hr>

**Expected:**

![image](https://user-images.githubusercontent.com/37060537/38161880-95b6270a-3509-11e8-821b-63729d8c7fa4.png)

**Generated:**

![image](https://user-images.githubusercontent.com/37060537/38161914-3db981ea-350a-11e8-8269-951fe0f7e4dc.png)

<hr>

**Expected:**

![image](https://user-images.githubusercontent.com/37060537/38162009-ddeebaee-350b-11e8-9003-3e43e04f0c24.png)

**Generated:**

![image](https://user-images.githubusercontent.com/37060537/38162006-c73117f2-350b-11e8-85f3-134659d60545.png)

**Comment by jsimpao** [comment]
The generated text incorporates the modifications specified by Oren for this page. Izza has already reverted the text to the expected output above in order to simulate pixel perfect design. Closing the issue for now.
