### ISSUE TITLE
Font size issues and missing dashes

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#40]
**Platform: Desktop & Mobile**

Under Technical Papers & Legal Circular section of Home page:
Kindly adjust font sizes to match expected output, and please add missing dashes as well.
Thanks!

Expected Result:
![expected pdf dashes](https://user-images.githubusercontent.com/37061492/38286145-54d934a8-37f6-11e8-8c08-afaaf8a4bcf3.PNG)

Actual Result:
![actual pdf dashes](https://user-images.githubusercontent.com/37061492/38286149-5b437916-37f6-11e8-8160-d60b8f317f1f.PNG)

**Comment by abry-ibinex** [comment]
Alignment issue still persists.
