### ISSUE TITLE
Pricing page layout is destroyed in Microsoft Edge

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#41]
**Platform: Desktop & Mobile**
Browser: Miscrosoft Edge

Expected Result:
![expected pricing - microsoft edge](https://user-images.githubusercontent.com/37061492/38287124-8e7b658c-37fb-11e8-9216-18371e0ae22d.PNG)

Actual Result:
![actual pricing - microsoft edge](https://user-images.githubusercontent.com/37061492/38287134-9d85b884-37fb-11e8-8667-b45148b4ac4d.PNG)

**Comment by abry-ibinex** [comment]
Thanks, Ace!
