### ISSUE TITLE
Ugly stretch

### ISSUE THREAD

**Issue by abry-ibinex** [acelabini/ibinex-option-one#43]
**Platform: Mobile
Screen width: ~950px**

## Note: Make sure the design for 320px width is still intact after applying your changes.

Actual result:
![image](https://user-images.githubusercontent.com/37060537/38287703-e237a242-3780-11e8-8a0a-9489ab14e469.png)

**Comment by markibinex** [comment]
please check @abry-ibinex

**Comment by abry-ibinex** [comment]
Fixed c448a16 thanks!
