### ISSUE TITLE
Misaligned paragraphs on 1024px width

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#44]
**Platform: iPad Pro (1024px width)**

In device having 1024px width, all paragraphs are misaligned.

Expected Result:
![expected paragraph alignment](https://user-images.githubusercontent.com/37061492/38288201-ce93b204-3801-11e8-97d6-f4cc6617f2ff.PNG)

![expected paragraph alignment 2](https://user-images.githubusercontent.com/37061492/38288203-d320ca6e-3801-11e8-8aa7-cc04c9c17f58.PNG)

Actual Result:
![actual paragraph alignment](https://user-images.githubusercontent.com/37061492/38288205-d92c889e-3801-11e8-8e49-b7478750850f.PNG)

![actual paragraph alignment 2](https://user-images.githubusercontent.com/37061492/38288208-dd0f3556-3801-11e8-9411-08953fd6d737.PNG)

**Comment by abry-ibinex** [comment]
Close but could be better. "Protection of funds" is still a bit higher than "Encryption and Technology" @seanibinex
