### ISSUE TITLE
Ibinex Media Coverage

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#45]
**Platform: Desktop & Mobile**

The following are issues with the Ibinex Media Coverage section:
1. In desktop view (actual result), media logos are too small and don't cover much of the page.
2. In mobile view (actual result), "Ibinex Media Coverage" title is bigger than the one in the expected result.

Expected Result:
Desktop
![expected media coverage - desktop](https://user-images.githubusercontent.com/37061492/38290275-0a065962-380d-11e8-8292-1ea4ea446fc6.PNG)

Actual Result:
Desktop
![actual media coverage - desktop](https://user-images.githubusercontent.com/37061492/38290291-1d2fa1ce-380d-11e8-91b4-71f5eae5a98f.PNG)

Expected Result:
Mobile
![expected media coverage - mobile](https://user-images.githubusercontent.com/37061492/38290285-13a85240-380d-11e8-8e9a-a1b1c67f5a64.PNG)

Actual Result:
Mobile
![actual media coverage - mobile](https://user-images.githubusercontent.com/37061492/38290299-26937b0a-380d-11e8-9097-10b6d9471333.PNG)

**Comment by jctiru-ibinex** [comment]
Fixed.

**Comment by jctiru-ibinex** [comment]
Please check commit f453e7261968fdc1f4b16eb3ea188541a7eff654.

**Comment by abry-ibinex** [comment]
It got even smaller @jctiru-ibinex 

Have a look again on how it's supposed to look like:
![expected media coverage - mobile](https://user-images.githubusercontent.com/37061492/38290285-13a85240-380d-11e8-8e9a-a1b1c67f5a64.PNG)

**Comment by abry-ibinex** [comment]
JS-sama!
