### ISSUE TITLE
The People Behind Ibinex

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#46]
**Platform: Desktop & Mobile**

Issues concerning "The people behind iBinex" section:

Desktop
1. When the first person is displayed, left arrow should have a fainter color.
2. Please review the size of the arrows and the distance between them.
3. Make the Linkedin Profile and Download CV links the same as the expected output.

Expected:
Desktop
![expected the people behind - desktop](https://user-images.githubusercontent.com/37061492/38292364-1401c146-3816-11e8-8de1-e45eb0231da4.PNG)

Actual:
Desktop
![actual the people behind - desktop](https://user-images.githubusercontent.com/37061492/38292377-1e37d6be-3816-11e8-8c13-6f907b79ab99.PNG)

Mobile
1. The section containing the name and title of the person should partly cover the image.
2. When the first person is displayed, left arrow should have a fainter color.
3. Please review the size of the arrows and the distance between them.
4. Make the Linkedin Profile link the same as the expected output, and hide the Download CV link in mobile view.

Expected:
Mobile
![expected the people behind - mobile](https://user-images.githubusercontent.com/37061492/38292399-33d76af2-3816-11e8-98a5-43a747e73036.PNG)

Actual:
Mobile
![actual the people behind - mobile](https://user-images.githubusercontent.com/37061492/38292416-3e201d60-3816-11e8-931b-6388d10665ed.PNG)

**Comment by jctiru-ibinex** [comment]
Issue closely related to https://github.com/acelabini/ibinex-option-one/issues/30.

**Comment by abry-ibinex** [comment]
Good catch.

**Comment by acelabini** [comment]
Maybe @kgsoriano17 can do this?

**Comment by kgsoriano17** [comment]
will look into it later.

**Comment by kgsoriano17** [comment]
try playing with negative margin top on #exec-slideshow? will try to fix it later if I have time.

**Comment by jsimpao** [comment]
Unable to close this issue due to the following unresolved issues:

Desktop
- Please review the size of the arrows and the distance between them.

Mobile
- Please review the size of the arrows and the distance between them.
- ...hide the Download CV link in mobile view.

**Comment by jctiru-ibinex** [comment]
Please check commit d0aee1c2da4820e2cac5994fdf8aaf99bf3a0e09.
