### ISSUE TITLE
Ibinex Advisory Board (mobile)

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#47]
**Platform: Mobile**

Issues with Ibinex Advisory Board (mobile):
1. In actual, Ibinex Advisory Board heading is missing.
2. In actual, chevron arrows are not exactly the same as in the expected output, and are not vertically centered on the image.
3. Please remove the word "of" in Jeremy Corbein's title. Thanks!

Expected Result:
![expected ibinex advisory board - mobile](https://user-images.githubusercontent.com/37061492/38293735-314b3c6e-381b-11e8-8157-c24d171c3871.PNG)

Actual Result:
![actual ibinex advisory board - mobile](https://user-images.githubusercontent.com/37061492/38293740-35221e2a-381b-11e8-865f-acd340a4b8f8.PNG)

**Comment by abry-ibinex** [comment]
Good shit, JC!

**Comment by abry-ibinex** [comment]
![image](https://user-images.githubusercontent.com/37060537/38345330-633c51c2-3843-11e8-93b8-6b383b6f970b.png)

**Comment by jctiru-ibinex** [comment]
Please check commit 7f627dc4bbcaacc49f3337b5c11e239d3bb213ad.

**Comment by abry-ibinex** [comment]
Thanks JC!
