### ISSUE TITLE
Ibinex Media Coverage capitalization

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#52]
**Platform: Desktop & Mobile**

Please display capitalization for the "Ibinex Media Coverage" text differently for desktop and mobile. Kindly do this for both the Home and About Us pages. Thanks!

Expected:
Home - Desktop
![expected media coverage - home - desktop](https://user-images.githubusercontent.com/37061492/38297013-b6d26664-3825-11e8-8f39-870041b1d3d8.PNG)

Expected:
Home - Mobile
![expected media coverage - home - mobile](https://user-images.githubusercontent.com/37061492/38297043-cff7367e-3825-11e8-89ff-2491fd3a80a5.PNG)

Expected:
About Us - Desktop
![expected media coverage - about us - desktop](https://user-images.githubusercontent.com/37061492/38297079-e77761ac-3825-11e8-8f34-2e0fc1084bc0.PNG)

Expected:
About Us - Mobile
![expected media coverage - about us - mobile](https://user-images.githubusercontent.com/37061492/38297112-fb5089f6-3825-11e8-9d0c-edb6af24f80b.PNG)

**Comment by jctiru-ibinex** [comment]
About us page capitalization already fixed. Please check d55c0527d8e9a098db4df5c4fcc360f00f09ff48.

**Comment by abry-ibinex** [comment]
Issue fixed thanks Kevin and JC!
