### ISSUE TITLE
Live Demo button too close to the edge

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#53]
**Platform: Desktop**

Live Demo button is too close to the right edge of the screen on certain resolution widths. Below are some widths where this phenomenon occurs.

Actual Result:
992px
![actual live demo screen edge - 992px](https://user-images.githubusercontent.com/37061492/38298190-50755e7c-3829-11e8-838c-2d20be4e4490.PNG)

Actual Result:
1100px
![actual live demo screen edge - 1100px](https://user-images.githubusercontent.com/37061492/38298215-5ede6b16-3829-11e8-9e29-da19557ae2c9.PNG)

**Comment by abry-ibinex** [comment]
Good shit
