### ISSUE TITLE
Bottom of Introducing CryptoBridge becomes jagged

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#56]
**Platform: Desktop & Mobile**

Bottom edge of "Introducing CryptoBridge" section becomes jagged/uneven between 769px ~ 1199px widths.

Actual Result:
769px
![actual introducing section jagged - 769px](https://user-images.githubusercontent.com/37061492/38300279-f95189b2-382e-11e8-9823-b32e03d69379.PNG)

Actual Result:
1199px
![actual introducing section jagged - 1199px](https://user-images.githubusercontent.com/37061492/38300311-0e28d7b4-382f-11e8-9edc-ff51d6b08072.PNG)

**Comment by abry-ibinex** [comment]
Thanks, Kevin!
