### ISSUE TITLE
Download buttons have basic look

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#60]
**Platform: Desktop & Mobile**

Why?

Expected Result:
![expected download button](https://user-images.githubusercontent.com/37061492/38301519-5ab3c302-3832-11e8-867d-5f5384b944a9.PNG)

Actual Result:
![actual download button](https://user-images.githubusercontent.com/37061492/38301529-61e3460c-3832-11e8-800e-2f917f692da1.PNG)

**Comment by abry-ibinex** [comment]
Fixed
