### ISSUE TITLE
4th and 6th fold's word spacings and dashes

### ISSUE THREAD

**Issue by abry-ibinex** [acelabini/ibinex-option-one#61]
Platform: Mobile

Note: Please make sure that you don't destroy desktop's design.

Expected result 4th fold:
![image](https://user-images.githubusercontent.com/37060537/38301597-dd7ae532-37b4-11e8-8aeb-675380caa4f1.png)

Actual result 4th fold:
![image](https://user-images.githubusercontent.com/37060537/38301556-c2521fdc-37b4-11e8-9bd3-a027992560da.png)

<hr>

Expected result 6th fold:
![image](https://user-images.githubusercontent.com/37060537/38301628-faa232c8-37b4-11e8-92cd-c111e2a3b663.png)

Actual result 6th fold:
![image](https://user-images.githubusercontent.com/37060537/38301649-0b8f7a5a-37b5-11e8-8c1f-53573f6b94d2.png)

**Comment by markibinex** [comment]
4th fold is hard af.

**Comment by abry-ibinex** [comment]
Mark, skip mo muna.
