### ISSUE TITLE
Laptop image disappears (992px~993px width)

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#71]
**Platform: Desktop**

Happens on 992px~993px width.

Expected Result:
![expected laptop image disappears](https://user-images.githubusercontent.com/37061492/38348113-847b0ca4-38d2-11e8-9c62-d3f5469e8728.PNG)

Actual Result:
![actual laptop image disappears](https://user-images.githubusercontent.com/37061492/38348121-92ba5356-38d2-11e8-9c4c-f3243a4cbf00.PNG)

**Comment by abry-ibinex** [comment]
Solved. Thanks, Ace!
