### ISSUE TITLE
Ibinex logo not aligned correctly

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#76]
**Platform: Desktop**

Ibinex logo is not aligned correctly with Risk Disclosure section.

Expected Result:
![expected ibinex logo pushed to left](https://user-images.githubusercontent.com/37061492/38354140-156cec92-38eb-11e8-86ef-47450e3a0233.PNG)

Actual Result:
![actual ibinex logo pushed to left](https://user-images.githubusercontent.com/37061492/38354146-1ae7a18a-38eb-11e8-94cb-f6eea40ab804.PNG)

**Comment by AnsellCC** [comment]
fixed along with #51
