### ISSUE TITLE
Missing blue tint on top side of currency ticker bar (mobile)

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#79]
**Platform: Mobile**

Expected Result:
![expected nav blue tint](https://user-images.githubusercontent.com/37061492/38360845-01d75b0a-38fe-11e8-97a4-7c1db5b879c4.PNG)
\
\
Actual Result:
![actual nav blue tint](https://user-images.githubusercontent.com/37061492/38360849-0764f992-38fe-11e8-9e7f-98608cd1f32d.PNG)

**Comment by AnsellCC** [comment]
Is this possible in CSS? @acelabini  @abry-ibinex  @jovitorrevillas  @markibinex

**Comment by jovitorrevillas** [comment]
Yes. Easier fix would be to add drop shadow effect on the menu at the top.
