### ISSUE TITLE
[ SERVICES ] Orientation and size of phone icon in nav/header

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#8]
Tester: Joel Simpao
OS: Windows 10
Browser: Chrome

Expected:
![expected nav phone icon](https://user-images.githubusercontent.com/37061492/38185890-cabe55f6-3682-11e8-8eb2-84f3a994b150.PNG)

Actual:
![actual nav phone icon](https://user-images.githubusercontent.com/37061492/38185899-d8b8b20a-3682-11e8-840e-0088c18f7263.PNG)

**Comment by AnsellCC** [comment]
fixed @ https://github.com/acelabini/ibinex-option-one/commit/502e07d36e1b0c5230c8f3c54b6c91e40fc58f13
