### ISSUE TITLE
Typographical errors

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#87]
**Platform: Mobile & Desktop**

Please fix all typographical errors for all affected words that appear multiple times in the page.

Expected Result:
![expected typo error - 1](https://user-images.githubusercontent.com/37061492/38401875-eb213b82-398a-11e8-850b-08055af2a9fa.PNG)

Actual Result:
![actual typo error - 1](https://user-images.githubusercontent.com/37061492/38401879-f3f6b30e-398a-11e8-9cb0-99a7d5f60b8c.PNG)

Expected Result:
![expected typo error - 2](https://user-images.githubusercontent.com/37061492/38401888-058c158c-398b-11e8-9d70-ae4af526c563.PNG)

Actual Result:
![actual typo error - 2](https://user-images.githubusercontent.com/37061492/38401893-0af8e75c-398b-11e8-88a9-78dada368eaa.PNG)

Expected Result:
![expected typo error - 3](https://user-images.githubusercontent.com/37061492/38401900-10de9c0c-398b-11e8-9e41-e098883c617c.PNG)

Actual Result:
![actual typo error - 3](https://user-images.githubusercontent.com/37061492/38401904-1819011a-398b-11e8-9d43-68734f07efa0.PNG)

Expected Result:
![expected typo error - 4](https://user-images.githubusercontent.com/37061492/38401907-1cdf4fd8-398b-11e8-9e3e-4bb3d1468453.PNG)

Actual Result:
![actual typo error - 4](https://user-images.githubusercontent.com/37061492/38401912-2273ab9c-398b-11e8-8a8c-a7938811f498.PNG)

**Comment by jsimpao** [comment]
Issue can't be closed due to the following reason:
 
For Stephen Colbert, expected is "Development Department, XB Software"
For some reason the word "Department" was removed with the fix.

**Comment by jctiru-ibinex** [comment]
Please check new commit debe7fa99bd7ea935ed1ca7350c7cfb589b9868c.
