### ISSUE TITLE
Advisory Board images look blurry

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#88]
**Platform: Mobile**

Advisory Board images look blurry on high mobile widths (i.e. 991px and below).

Actual Result:
![actual advisory board images stretched](https://user-images.githubusercontent.com/37061492/38402158-ede31da2-398c-11e8-8194-46fd9c32ddfc.PNG)

**Comment by acelabini** [comment]
Close this. @jsimpao
