### ISSUE TITLE
One Pager Brochure

### ISSUE THREAD

**Issue by jsimpao** [acelabini/ibinex-option-one#92]
**Platform: Mobile & Desktop**

Please correct the spelling.

Expected Result:
![expected one pager brochure](https://user-images.githubusercontent.com/37061492/38407864-bc42710a-39ad-11e8-90ea-2d4f620be49e.PNG)

Actual Result:
![actual one pager brochure](https://user-images.githubusercontent.com/37061492/38407881-c4899352-39ad-11e8-935d-e89ad8c191d0.PNG)

**Comment by jctiru-ibinex** [comment]
Auto closed, my bad.
